server:
  port: 8082
spring:
  config:
    activate:
      on-profile: default
  datasource:
    username: ${NBS_DBUSER}
    password: ${NBS_DBPASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE:40}
      connection-timeout: ${HIKARI_CON_TIMEOUT:300000}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:20}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:120000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1200000}
      pool-name: ${HIKARI_POOL_NAME:SQLServerHikariCP}
      leak-detection-threshold: ${LEAK_DETECTION_THRESHOLD:300000}
    odse:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;
    msgoute:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_MSGOUTE;encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none