DELETE FROM SERVICE_ACTION_PAIR;

INSERT INTO SERVICE_ACTION_PAIR (SERVICE, [ACTION], TOTAL_SERVICE_ACTION_PAIRS, SERIAL_NUMBER,
                                 MESSAGE_PROFILE_ID, CONDITION_CODE, STATUS_CODE, NOTES, CONCEPT_CODE)
VALUES (N'NND_Case_Note', N'send', 1, 1, N'Arbo_Case_Map_v1.0', NULL, N'ACTIVE',
        N'Arboviral Case Notification Message Mapping Guide v.1', NULL),
       (N'NND_Case_Note', N'send', 1, 2, N'CRS_MMG_V1.0', NULL, N'ACTIVE',
        N'Cogenital Rubella Syndrome Message Mapping Guide v.1.0', NULL),
       (N'NND_Case_Note', N'send', 1, 3, N'Gen_Case_Map_v1.0', NULL, N'ACTIVE',
        N'Generic Case Notification Message Mapping Guide v.1', NULL),
       (N'MVPS', N'send', 1, 4, N'Generic_MMG_V2.0', NULL, N'ACTIVE',
        N'Generic Case Notification Message Mapping Guide v.2', NULL),
       (N'NND_Case_Note', N'send', 1, 5, N'CongenitalSyphilis_MMG_V1.0', NULL, N'ACTIVE',
        N'Congenital Syphilis Case Notification Message Mapping Guide v.1', NULL),
       (N'NND_Case_Note', N'send', 1, 6, N'Hepatitis_MMG_V1.0', NULL, N'ACTIVE', N'Hepatitis Message Mapping Guide v1',
        NULL),
       (N'NND_Case_Note', N'send', 1, 7, N'Mumps_MMG_V1.0', NULL, N'ACTIVE', N'Mumps Message Mapping Guide v1.0', NULL),
       (N'NND_Case_Note', N'send', 1, 8, N'Pertussis_MMG_V1.0', NULL, N'ACTIVE',
        N'Pertussis Case Notification Message Mapping Guide v.1', NULL),
       (N'NND_Case_Note', N'send', 1, 9, N'STD_MMG_V1.0', NULL, N'ACTIVE',
        N'Sexually Transmitted Disease (STD) Message Mapping Guide v1', NULL),
       (N'NND_Case_Note', N'send', 1, 10, N'IPD_Case_Map_v1.0', NULL, N'ACTIVE',
        N'Streptococcus Pneumoniae Message Mapping Guide v1', NULL);
INSERT INTO SERVICE_ACTION_PAIR (SERVICE, [ACTION], TOTAL_SERVICE_ACTION_PAIRS, SERIAL_NUMBER,
                                 MESSAGE_PROFILE_ID, CONDITION_CODE, STATUS_CODE, NOTES, CONCEPT_CODE)
VALUES (N'NND_Case_Note', N'send', 1, 11, N'IPM_Case_Map_v1.0', NULL, N'ACTIVE',
        N'Influenza-Associated Pediatric Mortality Case Notification Message Mapping Guide v.1', NULL),
       (N'NND_Case_Note', N'send', 1, 12, N'MAL_Case_Map_v1.0', NULL, N'ACTIVE', N'Malaria Message Mapping Guide v1.0',
        NULL),
       (N'NND_Case_Note', N'send', 1, 13, N'Measles_MMG_V1.0', NULL, N'ACTIVE', N'Measles Message Mapping Guide v1.0',
        NULL),
       (N'NND_Case_Note', N'send', 1, 14, N'Rubella_MMG_V1.0', NULL, N'ACTIVE', N'Rubella Message Mapping Guide v1',
        NULL),
       (N'NND_Case_Note', N'send', 1, 15, N'TB_Case_Map_v2.0', NULL, N'ACTIVE',
        N'TB Case Notification Message Mapping Guide v.2', NULL),
       (N'NND_Case_Note', N'send', 1, 16, N'Var_Case_Map_v2.0', NULL, N'ACTIVE',
        N'Varicella Case Notification Message Mapping Guide v.2', NULL),
       (N'NND_Case_Note', N'send', 1, 17, N'Varicella_MMG_V3.0', NULL, N'ACTIVE',
        N'Varicella Case Notification Message Mapping Guide v.3', NULL),
       (N'MVPS_Onboard', N'send', 1, 18, N'TB_MMG_V3.0', 102201, N'ACTIVE',
        N'TB Case Notification Message Mapping Guide v.3', 102201),
       (N'MVPS_Onboard', N'send', 1, 19, N'TB_MMG_V3.0', 502582, N'ACTIVE',
        N'TB Case Notification Message Mapping Guide v.3', 502582),
       (N'TOTAL', N'', 19, NULL, N'', NULL, N'',
        N'This row is used to indicate the total ''count'' of rows to be processed; this is used by the Rhapsody process to ''cycle through'' the lookup table and ensure all mappings have been considered.',
        NULL);
