IF NOT EXISTS(
    SELECT 'X'
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'LOOKUP_MMWR')
BEGIN
CREATE TABLE LOOKUP_MMWR
(
    WEEK_ENDING DATE NOT NULL,
    MMWR_WEEK   INT  NOT NULL,
    MMWR_YEAR   INT  NOT NULL
);
END;
