IF NOT EXISTS(
    SELECT 'X'
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_NAME = 'LOOKUP_NNDLookup')
BEGIN
CREATE TABLE LOOKUP_NNDLookup
(
    NND_ID               VARCHAR(MAX)  NOT NULL,
    HL_LOC               VARCHAR(MAX)  NOT NULL,
    NND_LABEL            VARCHAR(MAX) NOT NULL,
    FROM_UNIQUE_ID       VARCHAR(MAX)  NOT NULL,
    FROM_QUESTION_NM     VARCHAR(MAX) NOT NULL,
    FROM_CODE_SET_NM     VARCHAR(MAX) NOT NULL,
    CONCEPT_CD           VARCHAR(MAX)  NOT NULL,
    CONCEPT_PREFERRED_NM VARCHAR(MAX) NOT NULL,
    FROM_CODE            VARCHAR(MAX)  NOT NULL,
    FROM_DISPLAY_NM      VARCHAR(MAX) NOT NULL,
    NBS_CLASS_CD         VARCHAR(MAX)  NOT NULL,
    TO_UNIQUE_ID         VARCHAR(MAX)  NOT NULL,
    TO_QUESTION_NM       VARCHAR(MAX) NOT NULL,
    TO_CODE_SET_NM       VARCHAR(MAX) NOT NULL,
    TO_CODE              VARCHAR(MAX)  NOT NULL,
    TO_DISPLAY_NM        VARCHAR(MAX) NOT NULL,
    NOTES                VARCHAR(MAX)
);
END;