CREATE TABLE LOOKUP_NNDLookup
(
    NND_ID               VARCHAR(50)  NOT NULL,
    HL_LOC               VARCHAR(50)  NOT NULL,
    NND_LABEL            VARCHAR(255) NOT NULL,
    FROM_UNIQUE_ID       VARCHAR(50)  NOT NULL,
    FROM_QUESTION_NM     VARCHAR(255) NOT NULL,
    FROM_CODE_SET_NM     VARCHAR(255) NOT NULL,
    CONCEPT_CD           VARCHAR(50)  NOT NULL,
    CONCEPT_PREFERRED_NM VARCHAR(255) NOT NULL,
    FROM_CODE            VARCHAR(50)  NOT NULL,
    FROM_DISPLAY_NM      VARCHAR(255) NOT NULL,
    NBS_CLASS_CD         VARCHAR(50)  NOT NULL,
    TO_UNIQUE_ID         VARCHAR(50)  NOT NULL,
    TO_QUESTION_NM       VARCHAR(255) NOT NULL,
    TO_CODE_SET_NM       VARCHAR(255) NOT NULL,
    TO_CODE              VARCHAR(50)  NOT NULL,
    TO_DISPLAY_NM        VARCHAR(255) NOT NULL,
    NOTES                VARCHAR(500)
);
