server:
  port: 8092

spring:
  application:
    name: case-notification-service

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    username: ${NBS_DBUSER}
    password: ${NBS_DBPASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
    odse:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;
    msg:
      url: jdbc:sqlserver://${NBS_DBSERVER};databaseName=NBS_MSGOUTE;encrypt=true;trustServerCertificate=true;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      maxPollIntervalMs: 30000
    thread: ${KAFKA_THREAD:1}
    group-id:
      std-group-id: std-processor-group
      non-std-group-id: non-std-processor-group
    topic:
      std-topic: std-topic
      non-std-topic: non-std-topic
service:
  timezone: ${SERVICE_TZ:UTC}