//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.15 at 12:17:27 PM EDT 
//


package gov.cdc.xmlhl7parserservice.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.cdc.xmlhl7parserservice.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.cdc.xmlhl7parserservice.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LabReportEvent }
     * 
     */
    public LabReportEvent createLabReportEvent() {
        return new LabReportEvent();
    }

    /**
     * Create an instance of {@link MessageElement }
     * 
     */
    public MessageElement createMessageElement() {
        return new MessageElement();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement }
     * 
     */
    public MessageElement.DataElement createMessageElementDataElement() {
        return new MessageElement.DataElement();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.EipDataType }
     * 
     */
    public MessageElement.DataElement.EipDataType createMessageElementDataElementEipDataType() {
        return new MessageElement.DataElement.EipDataType();
    }

    /**
     * Create an instance of {@link NBSNNDIntermediaryMessage }
     * 
     */
    public NBSNNDIntermediaryMessage createNBSNNDIntermediaryMessage() {
        return new NBSNNDIntermediaryMessage();
    }

    /**
     * Create an instance of {@link EiDataType }
     * 
     */
    public EiDataType createEiDataType() {
        return new EiDataType();
    }

    /**
     * Create an instance of {@link LabReportEvent.ResultedTest }
     * 
     */
    public LabReportEvent.ResultedTest createLabReportEventResultedTest() {
        return new LabReportEvent.ResultedTest();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.SnDataType }
     * 
     */
    public MessageElement.DataElement.SnDataType createMessageElementDataElementSnDataType() {
        return new MessageElement.DataElement.SnDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.SnunitDataType }
     * 
     */
    public MessageElement.DataElement.SnunitDataType createMessageElementDataElementSnunitDataType() {
        return new MessageElement.DataElement.SnunitDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.StDataType }
     * 
     */
    public MessageElement.DataElement.StDataType createMessageElementDataElementStDataType() {
        return new MessageElement.DataElement.StDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.TxDataType }
     * 
     */
    public MessageElement.DataElement.TxDataType createMessageElementDataElementTxDataType() {
        return new MessageElement.DataElement.TxDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.CxDataType }
     * 
     */
    public MessageElement.DataElement.CxDataType createMessageElementDataElementCxDataType() {
        return new MessageElement.DataElement.CxDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.IdDataType }
     * 
     */
    public MessageElement.DataElement.IdDataType createMessageElementDataElementIdDataType() {
        return new MessageElement.DataElement.IdDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.IsDataType }
     * 
     */
    public MessageElement.DataElement.IsDataType createMessageElementDataElementIsDataType() {
        return new MessageElement.DataElement.IsDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.CweDataType }
     * 
     */
    public MessageElement.DataElement.CweDataType createMessageElementDataElementCweDataType() {
        return new MessageElement.DataElement.CweDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.CeDataType }
     * 
     */
    public MessageElement.DataElement.CeDataType createMessageElementDataElementCeDataType() {
        return new MessageElement.DataElement.CeDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.TsDataType }
     * 
     */
    public MessageElement.DataElement.TsDataType createMessageElementDataElementTsDataType() {
        return new MessageElement.DataElement.TsDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.DtDataType }
     * 
     */
    public MessageElement.DataElement.DtDataType createMessageElementDataElementDtDataType() {
        return new MessageElement.DataElement.DtDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.NmDataType }
     * 
     */
    public MessageElement.DataElement.NmDataType createMessageElementDataElementNmDataType() {
        return new MessageElement.DataElement.NmDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.XtnDataType }
     * 
     */
    public MessageElement.DataElement.XtnDataType createMessageElementDataElementXtnDataType() {
        return new MessageElement.DataElement.XtnDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.XpnDataType }
     * 
     */
    public MessageElement.DataElement.XpnDataType createMessageElementDataElementXpnDataType() {
        return new MessageElement.DataElement.XpnDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.HdDataType }
     * 
     */
    public MessageElement.DataElement.HdDataType createMessageElementDataElementHdDataType() {
        return new MessageElement.DataElement.HdDataType();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.EipDataType.PlacerAssignedIdentifier }
     * 
     */
    public MessageElement.DataElement.EipDataType.PlacerAssignedIdentifier createMessageElementDataElementEipDataTypePlacerAssignedIdentifier() {
        return new MessageElement.DataElement.EipDataType.PlacerAssignedIdentifier();
    }

    /**
     * Create an instance of {@link MessageElement.DataElement.EipDataType.FillerAssignedIdentifier }
     * 
     */
    public MessageElement.DataElement.EipDataType.FillerAssignedIdentifier createMessageElementDataElementEipDataTypeFillerAssignedIdentifier() {
        return new MessageElement.DataElement.EipDataType.FillerAssignedIdentifier();
    }

}
