//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.04 at 01:27:35 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cdc.gov/NEDSS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.cdc.notificationprocessor.model;
