package gov.cdc.stdprocessorservice.model;


import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class Netss {
    String recordType = "";
    String update = "";
    String state = "";
    String year = "";
    String caseReportId = "";
    String siteCode = "";
    String week = "";
    String event = "";
    String count = "";
    String county = "";
    String dateOfBirth = "";
    String age = "";
    String ageType = "";
    String sex = "";
    String race = "";
    String hispanic = "";
    String eventDate = "";
    String caseStatus = "";
    String imported = "";
    String outbreak = "";
    String future = "";
    String infosrce = "";
    String methodCaseDetectn = "";
    String zip = "";
    String city = "";
    String pid = "";
    String pregnantInitExam = "";
    String origin = "";
    String dxDate = "";
    String specimenSource = "";
    String labSpecimenCollDate = "";
    String neurologicalInvolvment = "";
    String interview = "";
    String partner = "";
    String americanIndianAlaskanNative = "";
    String asian = "";
    String blackAfricanAmerican = "";
    String nativeHawaiianPacificIslander = "";
    String white = "";
    String otherRace = "";
    String refusedReportRace = "";
    String unknownRace = "";
    String hispanicLatino = "";
    String censusTract = "";
    String stdImport = "";
    String dateInitHealthExam = "";
    String dateFirstReportOfCase = "";
    String treatmentDate = "";
    String dateReportedToCdc = "";
    String hivStatus = "";
    String sexWithMale12m = "";
    String sexWithFemale12m = "";
    String sexWithAnnon12m = "";
    String sexWithPersonIdu12m = "";
    String sexWithPersonIntox12m = "";
    String sexExchDrugMoney = "";
    String sexPersonKnownToBeAnMsm = "";
    String injectionDrugUse = "";
    String crackUse = "";
    String cocianeUse = "";
    String heroinUse = "";
    String methamphetamineUse = "";
    String nitratesPoppers = "";
    String edUse = "";
    String otherDrugUse = "";
    String noDrugUse = "";
    String incarcerated = "";
    String priorStd = "";
    String sexPartnerThroughInternet = "";
    String totalNbrSexPartner12Month = "";
    String aAnusRectum = "";
    String bPenis = "";
    String cScrotum = "";
    String dVagina = "";
    String eCervix = "";
    String fNasopharynx = "";
    String gMouthOral = "";
    String hEyeConjunctiva = "";
    String iHead = "";
    String jTorso = "";
    String kExtremities = "";
    String nNoLesionNoted = "";
    String oOther = "";
    String uUnknown = "";
    String nonTreponemalSerologicTestForSyphilis = "";
    String quantitativeSyphilisTestResult = "";
    String netssVersion = "";

    String dateType = "";
}
