name: Build and push xml-hl7-parser-service image to ECR
on:
  push:
    branches:
      - main
      - master
      - update-github-action-**
    paths:
      - 'xml-hl7-parser-service/**'
jobs:
  extract-version-suffix:
    name: Extract image tag from version
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.parse.outputs.image_tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from build.gradle and extract suffix
        id: parse
        run: |
          version_line=$(grep "^version" ./xml-hl7-parser-service/build.gradle)
          version=$(echo "$version_line" | sed -E "s/version *= *['\"]([^'\"]+)['\"]/\1/")
          echo "Full version: $version"

          # Default value
          image_tag="SNAPSHOT"

          # Match SNAPSHOT-123
          if [[ "$version" =~ SNAPSHOT-([0-9]+) ]]; then
            image_tag="SNAPSHOT-${BASH_REMATCH[1]}"
          elif [[ "$version" =~ SNAPSHOT ]]; then
            image_tag="SNAPSHOT"
          fi

          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

  call-build-microservice-container-workflow:
    name: Build Container
    needs: extract-version-suffix
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: nnd-case-notification-service/xml-hl7-parser-service
      dockerfile_relative_path: -f ./xml-hl7-parser-service/Dockerfile .
      environment_classifier: ${{ needs.extract-version-suffix.outputs.image_tag }}
      java_version: "21"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  call-update-helm-xml-hl7-parser-service:
    name: Request DEV deployment
    needs: call-build-microservice-container-workflow
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: xml-hl7-parser-service
      values_file_with_path: charts/xml-hl7-parser-service/values-dts1.yaml
      new_image_tag: ${{ needs.call-build-microservice-container-workflow.outputs.output_image_tag }}
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}