name: Build and push data-extraction-service image to ECR
on:
  push:
    branches:
      - main
      - master
      - update-github-action-**
    paths:
      - 'data-extraction-service/**'
jobs:
#    sonar_scan:
#      uses: ./.github/workflows/sonar.yaml
#      secrets:
#        CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
#        PASSED_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  detect-classifier:
    runs-on: ubuntu-latest
    outputs:
      classifier: ${{ steps.extract-classifier.outputs.classifier }}
    steps:
      - uses: actions/checkout@v4

      - id: extract-classifier
        run: |
          version=$(grep "^version *= *" ./data-extraction-service/build.gradle | sed -E "s/version *= *['\"]?([^'\"]*)['\"]?/\1/")
          echo "Version is: $version"
          
          if [[ "$version" == *"-RELEASE" ]]; then
            echo "classifier=RELEASE" >> $GITHUB_OUTPUT
          else
            echo "classifier=SNAPSHOT" >> $GITHUB_OUTPUT
          fi


  call-build-microservice-container-workflow:
    name: Build Container
#    needs: sonar_scan
    needs: detect-classifier
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Build-gradle-microservice-container.yaml@main
    with:
      microservice_name: nnd-case-notification-service/data-extraction-service
      dockerfile_relative_path: -f ./data-extraction-service/Dockerfile .
      environment_classifier: ${{ needs.detect-classifier.outputs.classifier }}
      java_version: "21"
    secrets:
      CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
      ECR_REPO_BASE_NAME: ${{secrets.ECR_REPO_BASE_NAME}}
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}

  clean-up-classifier-env:
    name: Unset CLASSIFIER from environment
    run: |
      echo "Removing CLASSIFIER from env"
      echo "CLASSIFIER=" >> $GITHUB_ENV


  call-update-helm-data-extraction-service:
    name: Request DEV deployment
    needs: call-build-microservice-container-workflow
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Update-helm-charts.yaml@main
    with:
      microservice_name: data-extraction-service
      values_file_with_path: charts/data-extraction-service/values-dts1.yaml
      new_image_tag: ${{ needs.call-build-microservice-container-workflow.outputs.output_image_tag }}
    secrets:
      GIT_USER_EMAIL: ${{secrets.GIT_USER_EMAIL}}
      GIT_USER_NAME: ${{secrets.GIT_USER_NAME}}
      HELM_TOKEN: ${{secrets.HELM_TOKEN}}